version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    labels:
      - dependencies
    ignore:
      - dependency-name: wrangler
    schedule:
      interval: monthly
      time: "10:00"
      timezone: Asia/Seoul
    groups:
      npm-minor-patch:
        patterns:
          - "*"
        update-types:
          - minor
          - patch

  - package-ecosystem: cargo
    directory: "/"
    labels:
      - dependencies
    schedule:
      interval: monthly
      time: "10:00"
      timezone: Asia/Seoul
    groups:
      cargo-minor-patch:
        patterns:
          - "*"
        update-types:
          - minor
          - patch

  - package-ecosystem: github-actions
    directory: "/"
    labels:
      - dependencies
    schedule:
      interval: monthly
      time: "10:00"
      timezone: Asia/Seoul
    groups:
      github-actions-minor-patch:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
